---
title: "Housing Costs"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```

| County                   | Monthly Rent | Monthly HOC | Median Household Income | Registered Nurse Income | Percent Inc on Rent | Percent Inc on Home Ownership | RN Income on Rent | RN Income on Home Ownership | MOE_Rent | MOE_HOC | MOE_MedianHH |
|--------------------------|--------------|-------------|-------------------------|-------------------------|---------------------|-------------------------------|-------------------|-----------------------------|----------|---------|--------------|
| Canyon County, Idaho     | 10152        | 10968       | 49143                   | 62,890                  | 20.7                | 22.3                          | 16.1              | 17.4                        | 240      | 228     | 1598         |
| Payette County, Idaho    | 8916         | 10284       | 50289                   | 62,890                  | 17.7                | 20.4                          | 14.2              | 16.4                        | 780      | 804     | 3560         |
| Washington County, Idaho | 8052         | 7344        | 37206                   | 62,890                  | 21.6                | 19.7                          | 12.8              | 11.7                        | 480      | 636     | 3857         |
| Malheur County, Oregon   | 7968         | 8820        | 42478                   | 74,900                  | 18.8                | 20.8                          | 10.6              | 11.8                        | 312      | 1104    | 3046         |

## Mortgage Costs
```{r, include=F}
source("../Housing/Cost and affordability data/mortgage_cost_Data.R", local = knitr::knit_global())
```

```{r, echo=F, fig.height=6,fig.width=10}
ownerMap
```

## Rent Costs
```{r, include=F}
source("../Housing/Cost and affordability data/renter_cost_Data.R", local = knitr::knit_global())
```

```{r, echo=F, fig.height=6,fig.width=10}
ownerMap
```