---
title: "Industries and Occupations"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

The retail trade industry employs the most individuals in Malheur County (United States Census Bureau, County Business Patterns, 2012 to 2018). Establishments in retail trade include all retail stores, such as electronic stores, home and garden stores, grocery stores, and establishments of all sizes, from large box retailers to small businesses. Approximately 22 percent of all those employed in Malheur County worked in this industry, totaling approximately 1843 employees and $54 million in annual payroll. Between 2012 and 2018 the number of retail trade establishments decreased from 120 to 110. However, the total annual payroll increased from $46 million to $54 million, making it the second-highest industry by payroll (19.9 percent of the county’s annual payroll).

Payette County, on the other hand, only has 57 retail trade establishments. According to the County Business Patterns data for Payette County, only 8 percent of those who work in Payette County work in a retail trade establishment. This equates to approximately 460 individuals, a slight decrease from the 487 the industry employed in 2012. Stakeholders also noted a stark difference in retail establishments between the two regions. Most believe that retail establishments choose Malheur County over Idaho counties because of the preference consumers have for shopping in Oregon. Consumers prefer shopping in Oregon because of the state’s lack of sales tax and the legal status of marijuana. The purchase and possession of medicinal and recreational marijuana is illegal in Idaho. 

The health care and social assistance industry is the second largest employer in Malheur County. This industry includes hospitals, nursing facilities, and other health care providers and facilities. Between 2012 and 2018, the number of health care and social assistance establishments fell at a steady rate from 112 to 95 establishments. While the number of establishments decreased,  employment in the industry initially increased from 1538 in 2012 to 1635 in 2016. Following this initial increase, the number of those employed by the industry fell to 1410 between 2016 and 2018. Despite the decrease in establishment and employees, the total annual payroll increased from $53 million to $57 million. The health care and social assistance industry was also the top employer in the county by payroll. In 2018, 22.2 percent of the county’s annual payroll came from the health care industry.

Another important industry in Malheur County is manufacturing. Manufacturing establishments include traditional factory manufacturing of fertilizers, paper products, metals, and plastics. Manufacturing also includes the production of  animal food products, grain processing, food product manufacturing, meat processing, fruit and vegetable preservation, and beverage processing. In 2018, the industry contributed 42.8 million in annual payroll (14.2 percent of total annual payroll) and hired 1178 individuals (15.84 percent of total county employment) across 35 establishments. 
Payette County is also home to several manufacturing establishments. Like Malheur County, Payette County had approximately 33 establishments in 2018, hiring approximately 1500 individuals (23 percent of the workforce) and contributing $50.5 million in wages annually (23.8 percent of the total annual payroll). 


<font color = "orange">What jobs do people have?</font> The data available at the county level does not give us detailed data about occupations. However, data from the American Community Survey does give us a sense of the types of jobs individuals have. The majority of individuals in Malheur county work in management, business, and financial occupations (12.7 percent). Jobs that fall under this category include managers, CEOs, directors, human resources workers, accountants, insurance underwriters, for example (see <a href="https://www2.census.gov/programs-surveys/cps/methodology/Occupation%20Codes.pdf"> this source </a> for more). The second most common jobs are office administration and support roles (11.3 percent), followed by production occupations (8.4 percent). Production occupation jobs are primarily manufacturing jobs, including food processing. Payette County’s top occupation groups are sales occupations, office administration and support, and production occupations. 

#
#
<p style="text-align:right">
<a href="https://eobed-dspg.github.io/workFlowPage.html">Worker Flows >> </a></p>

<p style="text-align:right">
<a href="https://eobed-dspg.github.io/genPage,html"> << Back to General Main </a></p>